import assert from "node:assert/strict";
import { after, before, describe, it } from "node:test";
import { readFileSync } from "node:fs";
import { spawnSync } from "node:child_process";

describe("booking Agent UUID correction migration", { skip: process.env.RUN_BOOKING_DB_TESTS !== "1" }, () => {
  const container = `webook-booking-agent-test-${process.pid}`;
  const administrator = "00000000-0000-4000-8000-000000000001";
  const operator = "00000000-0000-4000-8000-000000000002";

  function sql(source: string, success = true): string {
    const result = spawnSync("docker", ["exec", "-i", container, "psql", "-U", "postgres", "-v", "ON_ERROR_STOP=1", "-At"], { input: source, encoding: "utf8" });
    if (success) assert.equal(result.status, 0, result.stderr);
    else assert.notEqual(result.status, 0, "query should fail");
    return `${result.stdout}${result.stderr}`;
  }

  const values = (agentId: string | null) => JSON.stringify({
    check_in: "2026-10-20", check_out: "2026-10-22", customer_id: 1,
    status: "waiting", quantity: 2, price_sell: 9000, price_max: 10000,
    extra_charge: 0, note: "test", insurance: 1000, extra_person: 2,
    checkin_time: "14:00", checkout_time: "12:00", agent_id: agentId,
  });

  before(async () => {
    const run = spawnSync("docker", ["run", "--rm", "-d", "--name", container, "-e", "POSTGRES_HOST_AUTH_METHOD=trust", "postgres:17-alpine"], { encoding: "utf8" });
    assert.equal(run.status, 0, run.stderr);
    for (let attempt = 0; attempt < 30; attempt++) {
      if (spawnSync("docker", ["exec", container, "pg_isready", "-U", "postgres"]).status === 0) break;
      await new Promise(resolve => setTimeout(resolve, 500));
    }
    sql(`
      create extension pgcrypto; create extension "uuid-ossp"; create extension btree_gist;
      create role anon; create role authenticated; create role service_role; create schema auth;
      create table auth.users(id uuid primary key);
      insert into auth.users values ('${administrator}'), ('${operator}');
      create table public.users(uid uuid primary key references auth.users(id), role_id smallint);
      insert into public.users values ('${administrator}',1), ('${operator}',2);
      create table public.banks(id uuid primary key);
      insert into public.banks values ('00000000-0000-4000-8000-000000000010');
      create table public.agents(id uuid primary key default gen_random_uuid(), name text not null, video_url text not null, is_active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz);
      create table public.agent_accounts(id uuid primary key default gen_random_uuid(), agent_id uuid not null references public.agents(id) on delete cascade, bank_id uuid not null references public.banks(id) on delete restrict, account_number text not null, created_at timestamptz not null default now(), unique(agent_id,bank_id,account_number));
      create index idx_agent_accounts_agent_id on public.agent_accounts(agent_id);
      create table public.listings(id uuid primary key, property_id bigint unique);
      insert into public.listings values ('00000000-0000-4000-8000-000000000100',990001);
      create table public.customers(id bigint primary key); insert into public.customers values(1);
      create table public.bookings(id bigint generated by default as identity primary key, booking_code text unique, listing_id uuid not null references public.listings(id), houseid bigint, customer_id bigint references public.customers(id), status text, check_in date, check_out date, quantity integer, price_sell numeric, price_max numeric, deposit_amount numeric, extra_charge numeric, note text, insurance numeric, extra_person numeric, checkin_time time, checkout_time time, updated_at timestamptz default now(), created_by uuid references auth.users(id), agent_id bigint);
      alter table public.bookings add exclude using gist(listing_id with =,daterange(check_in,check_out,'[)') with &&) where (status not in ('cancelled','rejected'));
      insert into public.agents(id,name,video_url,is_active) values ('00000000-0000-4000-8000-000000000101','Active Agent','https://example.test/active',true), ('00000000-0000-4000-8000-000000000102','Inactive Agent','https://example.test/inactive',false);
      insert into public.agent_accounts(id,agent_id,bank_id,account_number) values ('00000000-0000-4000-8000-000000000201','00000000-0000-4000-8000-000000000101','00000000-0000-4000-8000-000000000010','1234');
      insert into public.bookings(booking_code,listing_id,houseid,status,check_in,check_out,quantity,price_sell,price_max,deposit_amount,extra_charge,agent_id) values ('LEGACY','00000000-0000-4000-8000-000000000100',990001,'confirmed','2026-10-01','2026-10-02',1,0,0,0,0,99);
      grant usage on schema public,auth to service_role; grant all on all tables in schema public to service_role;
    `);
    sql(readFileSync(new URL("../supabase/migrations/20260929140000_booking_house_information_snapshot.sql", import.meta.url), "utf8"));
    sql(readFileSync(new URL("../supabase/migrations/20260929150000_booking_agent_numeric_id.sql", import.meta.url), "utf8"));
    sql("insert into public.bookings(booking_code,listing_id,houseid,status,check_in,check_out,quantity,price_sell,price_max,deposit_amount,extra_charge,agent_id) values ('NUMERIC-SELECTED','00000000-0000-4000-8000-000000000100',990001,'confirmed','2026-10-05','2026-10-06',1,0,0,0,0,(select id from public.agents where name='Active Agent'));");
    sql(readFileSync(new URL("../supabase/migrations/20260929160000_restore_booking_agent_uuid.sql", import.meta.url), "utf8"));
  });

  after(() => { spawnSync("docker", ["rm", "-f", container], { encoding: "utf8" }); });

  it("restores UUID Agent and account ownership while preserving mapped booking selections", () => {
    const migration = readFileSync(new URL("../supabase/migrations/20260929160000_restore_booking_agent_uuid.sql", import.meta.url), "utf8");
    assert.match(migration, /pg_catalog\.gen_random_uuid\(\)/);
    assert.match(sql("select pg_typeof(a.id)::text, pg_typeof(aa.agent_id)::text, aa.account_number from public.agents a join public.agent_accounts aa on aa.agent_id=a.id"), /uuid\|uuid\|1234/);
    assert.match(sql("select agent_id is null from public.bookings where booking_code='LEGACY'"), /^t\s*$/);
    assert.match(sql("select b.agent_id = a.id from public.bookings b join public.agents a on a.name='Active Agent' where b.booking_code='NUMERIC-SELECTED'"), /^t\s*$/);
  });

  it("allows only an administrator to assign an active UUID Agent through booking RPC", () => {
    const activeId = sql("select id from public.agents where name='Active Agent'").trim();
    const inactiveId = sql("select id from public.agents where name='Inactive Agent'").trim();
    assert.match(activeId, /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i);
    assert.match(sql(`set role service_role; select public.admin_create_house_booking(990001,'00000000-0000-4000-8000-000000000301','${administrator}','${values(activeId)}'::jsonb)`), /\d+/);
    assert.match(sql(`select agent_id from public.bookings where booking_code='BK-00000000-0000-4000-8000-000000000301'`), new RegExp(`^${activeId}\\s*$`));
    assert.match(sql(`select public.admin_create_house_booking(990001,'00000000-0000-4000-8000-000000000302','${administrator}','${values(inactiveId)}'::jsonb)`, false), /booking_agent_invalid/);
    assert.match(sql(`select public.admin_create_house_booking(990001,'00000000-0000-4000-8000-000000000303','${operator}','${values(activeId)}'::jsonb)`, false), /booking_agent_forbidden/);
    assert.match(sql(`select public.admin_create_house_booking(990001,'00000000-0000-4000-8000-000000000304','${administrator}','${values("not-a-uuid")}'::jsonb)`, false), /booking_invalid_input/);
  });
});
