import assert from "node:assert/strict";
import { after, before, describe, it } from "node:test";
import { spawnSync } from "node:child_process";
import { readFileSync } from "node:fs";

// Uses an isolated PostgreSQL container, never a configured Supabase environment.
describe("house booking RPC integration", { skip: process.env.RUN_BOOKING_DB_TESTS !== "1" }, () => {
  const container = `webook-booking-test-${process.pid}`;
  function sql(source: string, success = true) {
    const result = spawnSync("docker", ["exec", "-i", container, "psql", "-U", "postgres", "-v", "ON_ERROR_STOP=1", "-At"], { input: source, encoding: "utf8" });
    if (success) assert.equal(result.status, 0, result.stderr);
    else assert.notEqual(result.status, 0, "query should fail");
    return `${result.stdout}${result.stderr}`;
  }
  const actor = "00000000-0000-4000-8000-000000000001";
  const values = { check_in: "2026-09-28", check_out: "2026-10-04", status: "confirmed", customer_id: 1, quantity: 1, price_sell: 3900, price_max: 6900, extra_charge: 0, note: "test", insurance: 3000, extra_person: 300, checkin_time: "14:00:00", checkout_time: "12:00:00" };
  const call = (house = 1024, revision = "2026-09-18T00:00:00Z", v = values) => `select public.admin_update_house_booking(${house},1,'${revision}','${actor}','${JSON.stringify(v)}'::jsonb);`;
  const createCall = (request = "00000000-0000-4000-8000-000000000099", v = values) => `select public.admin_create_house_booking(1024,'${request}','${actor}','${JSON.stringify(v)}'::jsonb);`;
  before(async () => {
    const run = spawnSync("docker", ["run", "--rm", "-d", "--name", container, "-e", "POSTGRES_HOST_AUTH_METHOD=trust", "postgres:17-alpine"], { encoding: "utf8" });
    assert.equal(run.status, 0, run.stderr);
    let ready = false;
    for (let i = 0; i < 30; i++) {
      if (spawnSync("docker", ["exec", container, "pg_isready", "-U", "postgres"]).status === 0) { ready = true; break; }
      await new Promise(resolve => setTimeout(resolve, 500));
    }
    assert.ok(ready);
    sql(`create role anon; create role authenticated; create role service_role; create schema auth;
      create function auth.uid() returns uuid language sql as 'select nullif(current_setting(''request.jwt.claim.sub'',true),'''')::uuid';
      create table auth.users(id uuid primary key); insert into auth.users values ('${actor}');
      create extension btree_gist;
      create table public.listings(id uuid primary key,property_id bigint unique);
      insert into public.listings values ('00000000-0000-4000-8000-000000000010',1024);
      create table public.customers(id bigint primary key); insert into public.customers values(1);
      create table public.bookings(id bigint generated by default as identity primary key,listing_id uuid references public.listings,houseid bigint,customer_id bigint references public.customers,check_in date,check_out date,status text,quantity integer,price_sell numeric,price_max numeric,deposit_amount numeric,extra_charge numeric,note text,insurance numeric,extra_person numeric,updated_at timestamptz,booking_code text unique,created_by uuid);
      alter table public.bookings add exclude using gist(listing_id with =,daterange(check_in,check_out,'[)') with &&) where (status not in ('cancelled','rejected'));
      create table public.booking_logs(booking_id bigint,performed_by uuid references auth.users(id));
      create function public.test_audit() returns trigger language plpgsql as 'begin insert into public.booking_logs values(new.id,auth.uid());return new;end';
      create trigger audit after update on public.bookings for each row execute function public.test_audit();
      insert into public.bookings(id,listing_id,houseid,customer_id,check_in,check_out,status,quantity,price_sell,price_max,deposit_amount,extra_charge,note,insurance,extra_person,updated_at,booking_code,created_by) values(1,'00000000-0000-4000-8000-000000000010',1024,null,'2026-09-28','2026-10-03','confirmed',1,15000,0,5000,0,null,null,null,'2026-09-18T00:00:00Z',null,null);
      select setval(pg_get_serial_sequence('public.bookings','id'),1,true);
      grant usage on schema public,auth to service_role; grant all on all tables in schema public to service_role;`);
    sql(readFileSync(new URL("../supabase/migrations/20260929140000_booking_house_information_snapshot.sql", import.meta.url), "utf8"));
  });
  after(() => { spawnSync("docker", ["rm", "-f", container], { encoding: "utf8" }); });
  it("only the service role can invoke the mutation", () => {
    assert.match(sql(`set role authenticated; ${call()}`, false), /permission denied/);
  });
  it("rejects a booking substituted from another house", () => {
    assert.match(sql(call(999), false), /booking_not_found/);
  });
  it("rejects attempts to edit the unused deposit_amount", () => {
    assert.match(sql(call(1024, "2026-09-18T00:00:00Z", { ...values, deposit_amount: 99999 } as typeof values), false), /booking_invalid_input/);
    assert.match(sql("select deposit_amount from public.bookings where id=1"), /^5000\s/);
  });
  it("updates one stay, preserves its total and writes one correctly attributed audit record", () => {
    sql(`set role service_role; ${call()}`);
    assert.match(sql("select check_out,price_sell,customer_id,price_max,deposit_amount,extra_person,insurance,checkin_time,checkout_time from public.bookings where id=1"), /2026-10-04\|3900\|1\|6900\|5000\|300\|3000\|14:00:00\|12:00:00/);
    assert.match(sql("select count(*),min(performed_by::text) from public.booking_logs"), new RegExp(`1\\|${actor}`));
  });
  it("rejects a stale revision without logging a second update", () => {
    assert.match(sql(call(), false), /booking_stale/);
    assert.match(sql("select count(*) from public.booking_logs"), /^1\s/);
  });
  it("rejects invalid booking-specific house information", () => {
    const revision = sql("select updated_at from public.bookings where id=1").trim();
    assert.match(sql(call(1024, revision, { ...values, extra_person: -1 }), false), /booking_invalid_input/);
    assert.match(sql(call(1024, revision, { ...values, checkin_time: "25:00" }), false), /booking_invalid_input/);
    assert.match(sql(call(1024, revision, { ...values, extra_beds: 1 } as typeof values), false), /booking_invalid_input/);
    assert.match(sql(call(1024, revision, { ...values, insurance: "bad" } as unknown as typeof values), false), /booking_invalid_input/);
    assert.match(sql(call(1024, revision, { ...values, customer_id: "not-an-id" } as unknown as typeof values), false), /booking_invalid_input/);
    assert.match(sql(call(1024, revision, { ...values, check_in: "not-a-date" } as unknown as typeof values), false), /booking_invalid_input/);
  });
  it("snapshots production-named house information and creates idempotently", () => {
    const creation = { ...values, check_in: "2026-10-06", check_out: "2026-10-08" };
    const first = sql(`set role service_role; ${createCall("00000000-0000-4000-8000-000000000099", creation)}`).trim().split(/\r?\n/).at(-1) ?? "";
    const second = sql(`set role service_role; ${createCall("00000000-0000-4000-8000-000000000099", creation)}`).trim().split(/\r?\n/).at(-1) ?? "";
    assert.equal(second, first);
    assert.match(sql(`select insurance,extra_person,checkin_time,checkout_time from public.bookings where id=${first}`), /3000\|300\|14:00:00\|12:00:00/);
    assert.match(sql("select count(*) from public.bookings where booking_code = 'BK-00000000-0000-4000-8000-000000000099'"), /^1\s/);
  });
  it("retains database overlap protection and rolls back log/write together", () => {
    sql("insert into public.bookings(id,listing_id,houseid,customer_id,check_in,check_out,status,quantity,price_sell,deposit_amount,extra_charge,note,updated_at,price_max) values(3,'00000000-0000-4000-8000-000000000010',1024,null,'2026-10-04','2026-10-06','confirmed',1,10000,0,0,null,now(),null)");
    const revision = sql("select updated_at from public.bookings where id=1").trim();
    assert.match(sql(call(1024, revision, { ...values, check_out: "2026-10-05" }), false), /exclusion constraint/);
    assert.match(sql("select check_out from public.bookings where id=1"), /2026-10-04/);
    assert.match(sql("select count(*) from public.booking_logs"), /^1\s/);
  });
});
