"use client";

import Link from "next/link";
import { useMemo, useState, useTransition } from "react";
import { useRouter } from "next/navigation";

import { saveQuotationAction } from "../../../app/admin/quotations/actions";
import { calculateQuotation, formatThaiBahtText, type QuotationItemInput } from "../../../lib/quotation-calculator";
import { addQuotationCalendarDays } from "../../../lib/quotation-dates";
import type { CustomerSnapshot, QuotationPayload, SellerSnapshot } from "../../../lib/quotation-types";
import { Alert, AlertDescription } from "../../ui/alert";
import { Button } from "../../ui/button";
import { Input } from "../../ui/input";
import { Textarea } from "../../ui/textarea";

export interface QuotationEditorProps { documentNumber: string | null; initialPayload: QuotationPayload; }
type FieldProps = { children: React.ReactNode; error?: string; field: string; label: string };
type ItemProps = { calculation?: ReturnType<typeof calculateQuotation>; errors: Record<string, string>; index: number; item: QuotationItemInput; onMove: (direction: -1 | 1) => void; onRemove: () => void; onUpdate: <K extends keyof QuotationItemInput>(key: K, value: QuotationItemInput[K]) => void; totalItems: number };

function Field({ children, error, field, label }: FieldProps) { void field; return <label className="grid gap-1 text-sm"><span>{label}</span>{children}{error ? <span className="text-xs text-destructive">{error}</span> : null}</label>; }
function TextInput({ error, field, inputMode, label, onChange, value }: { error?: string; field: string; inputMode?: React.HTMLAttributes<HTMLInputElement>["inputMode"]; label?: string; onChange: (value: string) => void; value: string }) { const input = <><Input aria-invalid={Boolean(error)} aria-label={label ?? field} data-field={field} inputMode={inputMode} onChange={(event) => onChange(event.target.value)} value={value} />{error ? <span className="text-xs text-destructive">{error}</span> : null}</>; return label ? <Field error={undefined} field={field} label={label}>{input}</Field> : input; }
function Numeric({ error, field, label, onChange, value }: { error?: string; field: string; label?: string; onChange: (value: string) => void; value: string }) { return label ? <TextInput error={error} field={field} inputMode="decimal" label={label} onChange={onChange} value={value} /> : <><Input aria-invalid={Boolean(error)} aria-label={field} data-field={field} inputMode="decimal" onChange={(event) => onChange(event.target.value)} value={value} />{error ? <span className="text-xs text-destructive">{error}</span> : null}</>; }
function Totals({ bold, label, value }: { bold?: boolean; label: string; value: string }) { return <div className={bold ? "flex justify-between border-t pt-2 font-semibold" : "flex justify-between"}><span>{label}</span><output>{value}</output></div>; }
function positions(items: QuotationItemInput[]) { return items.map((item, index) => ({ ...item, position: index + 1 })); }

function ItemDetailsControls({ calculation, errors, index, item, onMove, onRemove, onUpdate, totalItems }: ItemProps) {
  const error = (field: string) => errors[`items.${index}.${field}`];
  return <>
    <div className="flex gap-1"><Button aria-label="เลื่อนขึ้น" disabled={index === 0} onClick={() => onMove(-1)} size="icon-xs" type="button">↑</Button><Button aria-label="เลื่อนลง" disabled={index === totalItems - 1} onClick={() => onMove(1)} size="icon-xs" type="button">↓</Button><Button aria-label="ลบรายการ" disabled={totalItems === 1} onClick={onRemove} size="icon-xs" type="button" variant="destructive">×</Button></div>
    <Input aria-label="SKU" className="mb-1" data-field={`items.${index}.sku`} onChange={(event) => onUpdate("sku", event.target.value)} placeholder="SKU" value={item.sku} />
    <Input aria-invalid={Boolean(error("name"))} aria-label="ชื่อรายการ" className="mb-1" data-field={`items.${index}.name`} onChange={(event) => onUpdate("name", event.target.value)} placeholder="รายการ" value={item.name} />
    <Textarea aria-label="รายละเอียด" data-field={`items.${index}.description`} onChange={(event) => onUpdate("description", event.target.value)} placeholder="รายละเอียด" value={item.description} />
  </>;
}

function ItemQuantityControls({ errors, index, item, onUpdate, labelled }: Pick<ItemProps, "errors" | "index" | "item" | "onUpdate"> & { labelled?: boolean }) { const error = (field: string) => errors[`items.${index}.${field}`]; return <div className="grid grid-cols-2 gap-2"><Numeric error={error("quantity")} field={`items.${index}.quantity`} label={labelled ? "จำนวน" : undefined} onChange={(value) => onUpdate("quantity", value)} value={item.quantity} /><TextInput field={`items.${index}.unit`} label={labelled ? "หน่วย" : undefined} onChange={(value) => onUpdate("unit", value)} value={item.unit} /></div>; }
function ItemPriceControls({ errors, index, item, onUpdate, labelled }: Pick<ItemProps, "errors" | "index" | "item" | "onUpdate"> & { labelled?: boolean }) { return <Numeric error={errors[`items.${index}.unitPrice`]} field={`items.${index}.unitPrice`} label={labelled ? "ราคา" : undefined} onChange={(value) => onUpdate("unitPrice", value)} value={item.unitPrice} />; }
function ItemDiscountControls({ errors, index, item, onUpdate, labelled }: Pick<ItemProps, "errors" | "index" | "item" | "onUpdate"> & { labelled?: boolean }) { const error = (field: string) => errors[`items.${index}.${field}`]; const select = <select aria-label={`items.${index}.discountType`} data-field={`items.${index}.discountType`} onChange={(event) => onUpdate("discountType", event.target.value === "amount" || event.target.value === "percent" ? event.target.value : null)} value={item.discountType ?? ""}><option value="">ไม่มี</option><option value="amount">บาท</option><option value="percent">%</option></select>; const typeControl = labelled ? <Field error={error("discountType")} field={`items.${index}.discountType`} label="ส่วนลด">{select}</Field> : <>{select}{error("discountType") ? <span className="text-xs text-destructive">{error("discountType")}</span> : null}</>; return <div className="grid grid-cols-2 gap-2">{typeControl}<Numeric error={error("discountValue")} field={`items.${index}.discountValue`} label={labelled ? "มูลค่า" : undefined} onChange={(value) => onUpdate("discountValue", value)} value={item.discountValue} /></div>; }
function ItemVatControls({ errors, index, item, onUpdate, labelled }: Pick<ItemProps, "errors" | "index" | "item" | "onUpdate"> & { labelled?: boolean }) { const error = (field: string) => errors[`items.${index}.${field}`]; const select = <select aria-label={`items.${index}.vatTreatment`} data-field={`items.${index}.vatTreatment`} onChange={(event) => onUpdate("vatTreatment", event.target.value as QuotationItemInput["vatTreatment"])} value={item.vatTreatment}><option value="taxable">VAT</option><option value="exempt">ยกเว้น VAT</option><option value="none">ไม่คิด VAT</option></select>; const treatmentControl = labelled ? <Field error={error("vatTreatment")} field={`items.${index}.vatTreatment`} label="VAT">{select}</Field> : <>{select}{error("vatTreatment") ? <span className="text-xs text-destructive">{error("vatTreatment")}</span> : null}</>; return <div className="grid grid-cols-2 gap-2">{treatmentControl}<Numeric error={error("vatRate")} field={`items.${index}.vatRate`} label={labelled ? "อัตรา" : undefined} onChange={(value) => onUpdate("vatRate", value)} value={item.vatRate} /></div>; }
function ItemControls(props: ItemProps) { return <><ItemDetailsControls {...props} /><ItemQuantityControls {...props} labelled /><ItemPriceControls {...props} labelled /><ItemDiscountControls {...props} labelled /><ItemVatControls {...props} labelled /><p className="text-right font-medium">รวม {props.calculation?.lines[props.index]?.lineTotal ?? "—"}</p></>; }

export function QuotationEditor({ documentNumber: initialDocumentNumber, initialPayload }: QuotationEditorProps) {
  const router = useRouter();
  const [payload, setPayload] = useState<QuotationPayload>(initialPayload);
  const [documentNumber, setDocumentNumber] = useState(initialDocumentNumber);
  const [fieldErrors, setFieldErrors] = useState<Record<string, string>>({});
  const [formError, setFormError] = useState("");
  const [isDirty, setIsDirty] = useState(false);
  const [isPending, startTransition] = useTransition();
  const [logoUnavailable, setLogoUnavailable] = useState(false);
  const [sellerExpanded, setSellerExpanded] = useState(false);
  const calculationResult = useMemo(() => { try { return { calculation: calculateQuotation(payload), calculationError: "" }; } catch (error) { return { calculation: null, calculationError: error instanceof Error ? error.message : "คำนวณยอดไม่ได้" }; } }, [payload]);
  const { calculation, calculationError } = calculationResult;
  const total = (value?: string) => value ?? "—";
  function changed(field: string) { setIsDirty(true); setFieldErrors((current) => { const next = { ...current }; delete next[field]; return next; }); }
  function updateRoot<K extends keyof QuotationPayload>(key: K, value: QuotationPayload[K]) { changed(String(key)); setPayload((current) => ({ ...current, [key]: value })); }
  function updateSeller<K extends keyof SellerSnapshot>(key: K, value: SellerSnapshot[K]) { changed(`seller.${String(key)}`); setPayload((current) => ({ ...current, seller: { ...current.seller, [key]: value } })); }
  function updateCustomer<K extends keyof CustomerSnapshot>(key: K, value: CustomerSnapshot[K]) { changed(`customer.${String(key)}`); setPayload((current) => ({ ...current, customer: { ...current.customer, [key]: value } })); }
  function updateSellerOfficeType(officeType: SellerSnapshot["officeType"]) { changed("seller.officeType"); setPayload((current) => ({ ...current, seller: { ...current.seller, branchNumber: officeType === "branch" ? current.seller.branchNumber : "", officeType } })); }
  function updateCustomerOfficeType(officeType: CustomerSnapshot["officeType"]) { changed("customer.officeType"); setPayload((current) => ({ ...current, customer: { ...current.customer, branchNumber: officeType === "branch" ? current.customer.branchNumber : "", officeType } })); }
  function updateItem<K extends keyof QuotationItemInput>(index: number, key: K, value: QuotationItemInput[K]) { changed(`items.${index}.${String(key)}`); setPayload((current) => ({ ...current, items: current.items.map((item, itemIndex) => itemIndex === index ? { ...item, [key]: value } : item) })); }
  function addItem() { changed("items"); setPayload((current) => ({ ...current, items: positions([...current.items, { description: "", discountType: null, discountValue: "0", id: crypto.randomUUID(), name: "", position: 0, quantity: "1", sku: "", unit: "", unitPrice: "0.00", vatRate: "7.00", vatTreatment: "taxable" }]) })); }
  function removeItem(index: number) { if (payload.items.length > 1) { changed("items"); setPayload((current) => ({ ...current, items: positions(current.items.filter((_, itemIndex) => itemIndex !== index)) })); } }
  function moveItem(index: number, direction: -1 | 1) { const target = index + direction; if (target < 0 || target >= payload.items.length) return; changed("items"); setPayload((current) => { const items = [...current.items]; [items[index], items[target]] = [items[target]!, items[index]!]; return { ...current, items: positions(items) }; }); }
  function recalculateValidUntil(issueDate: string, validityDays: string, validUntil: string) { try { return addQuotationCalendarDays(issueDate, Number(validityDays)); } catch { return validUntil; } }
  function updateIssueDate(value: string) { changed("issueDate"); setPayload((current) => ({ ...current, issueDate: value, validUntil: current.validityDays ? recalculateValidUntil(value, current.validityDays, current.validUntil) : current.validUntil })); }
  function updateValidityDays(value: string) { changed("validityDays"); setPayload((current) => ({ ...current, validityDays: value, validUntil: value ? recalculateValidUntil(current.issueDate, value, current.validUntil) : current.validUntil })); }
  function focusField(field: string) { document.querySelector<HTMLElement>(`[data-field="${CSS.escape(field)}"]`)?.focus(); }
  const focusableFieldErrors = Object.entries(fieldErrors).filter(([field]) => field === "items" || field === "seller.logoUrl" || document.querySelector(`[data-field="${CSS.escape(field)}"]`)).map(([field, message]) => ({ field, message }));
  function save() { setFormError(""); startTransition(async () => { const result = await saveQuotationAction(payload); if (!result.ok) { setFieldErrors(result.fieldErrors); setFormError(result.formError); const firstField = Object.keys(result.fieldErrors)[0]; if (firstField) requestAnimationFrame(() => focusField(firstField)); return; } setPayload((current) => ({ ...current, id: result.id })); setDocumentNumber(result.documentNumber); setFieldErrors({}); setIsDirty(false); if (!payload.id) router.replace(`/admin/quotations/${encodeURIComponent(result.id)}?saved=1`); else router.refresh(); }); }
  const itemProps = (item: QuotationItemInput, index: number): ItemProps => ({ calculation: calculation ?? undefined, errors: fieldErrors, index, item, onMove: (direction) => moveItem(index, direction), onRemove: () => removeItem(index), onUpdate: (key, value) => updateItem(index, key, value), totalItems: payload.items.length });

  return <div className="space-y-4" data-dirty={isDirty} data-quotation-editor>
    <header className="flex flex-wrap items-start justify-between gap-3 border-b pb-3"><div><h1 className="text-xl font-semibold">{documentNumber ? "แก้ไขใบเสนอราคา" : "สร้างใบเสนอราคา"}</h1><p className="text-sm text-primary">{documentNumber ?? "เลขที่ออกเมื่อบันทึก"}</p></div><div className="flex items-center gap-2" data-header-actions><Button asChild variant="outline"><Link href="/admin/quotations">กลับ</Link></Button><Button disabled={isPending} onClick={save} type="button">{isPending ? "กำลังบันทึก" : "บันทึก"}</Button></div></header>
    {formError ? <Alert variant="destructive"><AlertDescription>{formError}</AlertDescription></Alert> : null}{focusableFieldErrors.length ? <Alert variant="destructive"><AlertDescription>{focusableFieldErrors.map(({ field, message }) => <button className="mr-2 underline" key={field} onClick={() => focusField(field)} type="button">{message}</button>)}</AlertDescription></Alert> : null}{calculationError ? <Alert variant="destructive"><AlertDescription>{calculationError}</AlertDescription></Alert> : null}
    <section className="flex flex-wrap items-center justify-between gap-4 border-b pb-3" data-seller-actions><div className="flex min-w-0 items-center gap-3">{payload.seller.logoUrl && !logoUnavailable ? <img alt="โลโก้ผู้ขาย" className="max-h-12 max-w-24 object-contain" onError={() => setLogoUnavailable(true)} src={payload.seller.logoUrl} /> : <div className="grid h-10 w-16 place-items-center rounded border text-xs text-muted-foreground">โลโก้</div>}<div className="min-w-0"><p className="truncate font-medium">{payload.seller.name || "ยังไม่มีชื่อผู้ขาย"}</p><p className="truncate text-sm text-muted-foreground">{payload.seller.officeType === "branch" ? `สาขา ${payload.seller.branchNumber || "-"}` : "สำนักงานใหญ่"}{payload.seller.taxId ? ` · ${payload.seller.taxId}` : ""}</p></div><Button onClick={() => setSellerExpanded((open) => !open)} size="sm" type="button" variant="ghost">แก้ไขเฉพาะใบ</Button></div><div data-document-actions /></section>
    {sellerExpanded ? <section className="grid gap-3 rounded-lg border p-4 md:grid-cols-2" data-seller-edit><TextInput error={fieldErrors["seller.name"]} field="seller.name" label="ผู้ขาย" onChange={(value) => updateSeller("name", value)} value={payload.seller.name} /><Field error={fieldErrors["seller.address"]} field="seller.address" label="ที่อยู่"><Textarea data-field="seller.address" onChange={(event) => updateSeller("address", event.target.value)} value={payload.seller.address} /></Field><TextInput error={fieldErrors["seller.taxId"]} field="seller.taxId" label="เลขผู้เสียภาษี" onChange={(value) => updateSeller("taxId", value)} value={payload.seller.taxId} /><Field error={fieldErrors["seller.officeType"]} field="seller.officeType" label="สำนักงานผู้ขาย"><select data-field="seller.officeType" onChange={(event) => updateSellerOfficeType(event.target.value === "branch" ? "branch" : "head_office")} value={payload.seller.officeType}><option value="head_office">สำนักงานใหญ่</option><option value="branch">สาขา</option></select></Field>{payload.seller.officeType === "branch" ? <TextInput error={fieldErrors["seller.branchNumber"]} field="seller.branchNumber" label="เลขสาขาผู้ขาย" onChange={(value) => updateSeller("branchNumber", value)} value={payload.seller.branchNumber} /> : null}<TextInput error={fieldErrors["seller.phone"]} field="seller.phone" label="โทรศัพท์" onChange={(value) => updateSeller("phone", value)} value={payload.seller.phone} /><TextInput error={fieldErrors["seller.email"]} field="seller.email" label="อีเมล" onChange={(value) => updateSeller("email", value)} value={payload.seller.email} /><TextInput error={fieldErrors["seller.website"]} field="seller.website" label="เว็บไซต์" onChange={(value) => updateSeller("website", value)} value={payload.seller.website} /></section> : null}
    <div className="grid items-start gap-4 lg:grid-cols-[minmax(390px,520px)_minmax(36px,1fr)_minmax(340px,430px)]"><section className="grid gap-3 rounded-lg border p-4 lg:col-start-1" data-customer-section><h2 className="font-semibold">ลูกค้า</h2><TextInput error={fieldErrors["customer.name"]} field="customer.name" label="ชื่อลูกค้า" onChange={(value) => updateCustomer("name", value)} value={payload.customer.name} /><Field error={fieldErrors["customer.address"]} field="customer.address" label="ที่อยู่"><Textarea data-field="customer.address" onChange={(event) => updateCustomer("address", event.target.value)} value={payload.customer.address} /></Field><TextInput error={fieldErrors["customer.taxId"]} field="customer.taxId" label="เลขผู้เสียภาษี" onChange={(value) => updateCustomer("taxId", value)} value={payload.customer.taxId} /><Field error={fieldErrors["customer.officeType"]} field="customer.officeType" label="สำนักงานลูกค้า"><select data-field="customer.officeType" onChange={(event) => updateCustomerOfficeType(event.target.value === "branch" ? "branch" : "head_office")} value={payload.customer.officeType}><option value="head_office">สำนักงานใหญ่</option><option value="branch">สาขา</option></select></Field>{payload.customer.officeType === "branch" ? <TextInput error={fieldErrors["customer.branchNumber"]} field="customer.branchNumber" label="เลขสาขาลูกค้า" onChange={(value) => updateCustomer("branchNumber", value)} value={payload.customer.branchNumber} /> : null}<TextInput error={fieldErrors["customer.contactName"]} field="customer.contactName" label="ผู้ติดต่อ" onChange={(value) => updateCustomer("contactName", value)} value={payload.customer.contactName} /><TextInput error={fieldErrors["customer.phone"]} field="customer.phone" label="โทรศัพท์" onChange={(value) => updateCustomer("phone", value)} value={payload.customer.phone} /><TextInput error={fieldErrors["customer.email"]} field="customer.email" label="อีเมล" onChange={(value) => updateCustomer("email", value)} value={payload.customer.email} /><Field error={fieldErrors["customer.shippingAddress"]} field="customer.shippingAddress" label="ที่อยู่จัดส่ง"><Textarea data-field="customer.shippingAddress" onChange={(event) => updateCustomer("shippingAddress", event.target.value)} value={payload.customer.shippingAddress} /></Field><Field error={fieldErrors["customer.serviceLocation"]} field="customer.serviceLocation" label="สถานที่บริการ"><Textarea data-field="customer.serviceLocation" onChange={(event) => updateCustomer("serviceLocation", event.target.value)} value={payload.customer.serviceLocation} /></Field></section>
      <section className="grid gap-3 rounded-lg border p-4 lg:col-start-3" data-document-section><h2 className="font-semibold">ข้อมูลเอกสาร</h2><Field error={fieldErrors.issueDate} field="issueDate" label="วันที่ออก"><Input data-field="issueDate" onChange={(event) => updateIssueDate(event.target.value)} type="date" value={payload.issueDate} /></Field><TextInput error={fieldErrors.validityDays} field="validityDays" inputMode="numeric" label="จำนวนวัน" onChange={updateValidityDays} value={payload.validityDays} /><Field error={fieldErrors.validUntil} field="validUntil" label="ใช้ได้ถึง"><Input data-field="validUntil" onChange={(event) => { changed("validUntil"); setPayload((current) => ({ ...current, validUntil: event.target.value, validityDays: "" })); }} type="date" value={payload.validUntil} /></Field><Field field="currency" label="สกุลเงิน"><Input data-field="currency" readOnly value="THB — บาท" /></Field><TextInput error={fieldErrors.reference} field="reference" label="เลขอ้างอิง" onChange={(value) => updateRoot("reference", value)} value={payload.reference} /></section></div>
    <section className="space-y-3"><Field error={fieldErrors.priceMode} field="priceMode" label="รูปแบบราคา"><select data-field="priceMode" onChange={(event) => updateRoot("priceMode", event.target.value as QuotationPayload["priceMode"])} value={payload.priceMode}><option value="vat_exclusive">ไม่รวม VAT</option><option value="vat_inclusive">รวม VAT</option></select></Field><div className="flex items-center justify-between"><h2 className="font-semibold">รายการ</h2><Button onClick={addItem} size="sm" type="button">เพิ่มรายการ</Button></div><div className="hidden overflow-x-auto md:block" data-item-table><table className="w-full min-w-[800px] text-sm"><thead><tr><th>รายการ</th><th>จำนวน/หน่วย</th><th>ราคา</th><th>ส่วนลด</th><th>VAT</th><th>รวม</th></tr></thead><tbody>{payload.items.map((item, index) => <tr className="border-t align-top" key={item.id}><td className="p-2"><ItemDetailsControls {...itemProps(item, index)} /></td><td className="p-2"><ItemQuantityControls {...itemProps(item, index)} /></td><td className="p-2"><ItemPriceControls {...itemProps(item, index)} /></td><td className="p-2"><ItemDiscountControls {...itemProps(item, index)} /></td><td className="p-2"><ItemVatControls {...itemProps(item, index)} /></td><td className="p-2 text-right">{calculation?.lines[index]?.lineTotal ?? "—"}</td></tr>)}</tbody></table></div><div className="grid gap-3 md:hidden" data-item-cards>{payload.items.map((item, index) => <article className="rounded-lg border p-3" key={item.id}><ItemControls {...itemProps(item, index)} /></article>)}</div></section>
    <div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_360px]"><section data-public-notes><Field error={fieldErrors.publicNotes} field="publicNotes" label="หมายเหตุ"><Textarea data-field="publicNotes" onChange={(event) => updateRoot("publicNotes", event.target.value)} value={payload.publicNotes} /></Field></section><section className="space-y-2" data-quotation-totals><Field error={fieldErrors.documentDiscountType} field="documentDiscountType" label="ส่วนลดเอกสาร"><select data-field="documentDiscountType" onChange={(event) => updateRoot("documentDiscountType", event.target.value === "amount" || event.target.value === "percent" ? event.target.value : null)} value={payload.documentDiscountType ?? ""}><option value="">ไม่มี</option><option value="amount">บาท</option><option value="percent">%</option></select></Field><Numeric error={fieldErrors.documentDiscountValue} field="documentDiscountValue" label="มูลค่าส่วนลดเอกสาร" onChange={(value) => updateRoot("documentDiscountValue", value)} value={payload.documentDiscountValue} /><Totals label="รวมก่อนส่วนลด" value={total(calculation?.subtotal)} /><Totals label="ส่วนลดรายการ" value={total(calculation?.itemDiscountTotal)} /><Totals label="ส่วนลดเอกสาร" value={total(calculation?.documentDiscountTotal)} /><Totals label="มูลค่าก่อน VAT" value={total(calculation?.taxableTotal)} /><Totals label="VAT" value={total(calculation?.vatTotal)} /><Totals bold label="ยอดรวมสุทธิ (THB)" value={total(calculation?.grandTotal)} /><p className="text-sm">{calculation ? formatThaiBahtText(calculation.grandTotal) : "—"}</p></section></div>
    <section className="rounded-xl border p-4" data-internal-notes data-field="items" tabIndex={-1}>{fieldErrors.items ? <span className="text-xs text-destructive">{fieldErrors.items}</span> : null}<Field error={fieldErrors.internalNotes} field="internalNotes" label="หมายเหตุภายใน (ไม่แสดงในเอกสาร)"><Textarea data-field="internalNotes" onChange={(event) => updateRoot("internalNotes", event.target.value)} value={payload.internalNotes} /></Field></section>
  </div>;
}
