import { build } from "esbuild";
import { injectManifest } from "workbox-build";
import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");

export async function buildPwa({ destination = join(root, "public/sw.js"), publicDirectory = join(root, "public") } = {}) {
  const temporaryDirectory = await mkdtemp(join(tmpdir(), "webook-pwa-"));
  try {
    const bundledWorker = join(temporaryDirectory, "sw.js");
    await build({
      entryPoints: [join(root, "worker/pwa-sw.js")],
      outfile: bundledWorker,
      bundle: true,
      format: "iife",
      platform: "browser",
      target: ["es2020"],
      minify: true,
      legalComments: "none",
      define: { "process.env.NODE_ENV": '"production"' },
      banner: { js: "/* Generated by npm run build:pwa from worker/pwa-sw.js. Do not edit. */" },
    });
    const result = await injectManifest({
      swSrc: bundledWorker,
      swDest: destination,
      globDirectory: publicDirectory,
      globPatterns: [
        "pwa/offline.html", "pwa/offline.js", "pwa/icon-192.png",
        "pwa/icon-512.png", "pwa/apple-touch-icon.png",
      ],
      modifyURLPrefix: { "": "/" },
    });
    if (result.warnings.length || result.count !== 5) {
      throw new Error(`PWA requires exactly five public assets: ${result.warnings.join("; ")}`);
    }
    return result;
  } finally {
    // mkdtemp creates this exact task-owned directory beneath the OS temp root.
    await rm(temporaryDirectory, { recursive: true, force: true });
  }
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const result = await buildPwa();
  console.log(`PWA: precached ${result.count} public assets (${result.size} bytes).`);
}
