import { build } from "esbuild";
import { injectManifest } from "workbox-build";
import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { createHash } from "node:crypto";
import { readdirSync, readFileSync, existsSync } from "node:fs";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");

// Fingerprint shipped source, never environment files or credentials. Normalize
// line endings so Windows and Linux generate the same release identity.
export function releaseRevision(sourceRoot = root) {
  const hash = createHash("sha256");
  function visit(relative) {
    const path = join(sourceRoot, relative);
    if (!existsSync(path)) return;
    const entries = readdirSync(path, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name, "en"));
    for (const entry of entries) {
      const file = `${relative}/${entry.name}`;
      if (entry.isDirectory()) visit(file);
      else if (entry.isFile() && /\.(?:tsx?|jsx?|mjs|css|json)$/.test(entry.name)) {
        hash.update(file).update("\0").update(readFileSync(join(sourceRoot, file), "utf8").replace(/\r\n/g, "\n")).update("\0");
      }
    }
  }
  for (const directory of ["app", "components", "hooks", "types", "styles", "lib", "server", "worker"]) visit(directory);
  for (const file of ["package.json", "package-lock.json", "next.config.ts", "open-next.config.ts", "postcss.config.mjs", "tsconfig.json", "scripts/build-pwa.mjs"]) {
    const path = join(sourceRoot, file);
    if (existsSync(path)) hash.update(file).update("\0").update(readFileSync(path, "utf8").replace(/\r\n/g, "\n")).update("\0");
  }
  return hash.digest("hex");
}

export async function buildPwa({ destination = join(root, "public/sw.js"), publicDirectory = join(root, "public") } = {}) {
  const temporaryDirectory = await mkdtemp(join(tmpdir(), "webook-pwa-"));
  try {
    const bundledWorker = join(temporaryDirectory, "sw.js");
    await build({
      entryPoints: [join(root, "worker/pwa-sw.js")],
      outfile: bundledWorker,
      bundle: true,
      format: "iife",
      platform: "browser",
      target: ["es2020"],
      minify: true,
      legalComments: "none",
      define: { "process.env.NODE_ENV": '"production"' },
      banner: { js: `/* Generated by npm run build:pwa. App revision: ${releaseRevision()}. Do not edit. */` },
    });
    const result = await injectManifest({
      swSrc: bundledWorker,
      swDest: destination,
      globDirectory: publicDirectory,
      globPatterns: [
        "pwa/offline.html", "pwa/offline.js", "pwa/icon-192.png",
        "pwa/icon-512.png", "pwa/apple-touch-icon.png",
      ],
      modifyURLPrefix: { "": "/" },
    });
    if (result.warnings.length || result.count !== 5) {
      throw new Error(`PWA requires exactly five public assets: ${result.warnings.join("; ")}`);
    }
    return result;
  } finally {
    // mkdtemp creates this exact task-owned directory beneath the OS temp root.
    await rm(temporaryDirectory, { recursive: true, force: true });
  }
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const result = await buildPwa();
  console.log(`PWA: precached ${result.count} public assets (${result.size} bytes).`);
}
