create extension btree_gist;
create role anon;
create role authenticated;
create role service_role;
create schema auth;
create function auth.uid() returns uuid language sql as $$ select nullif(current_setting('request.jwt.claim.sub', true), '')::uuid $$;
create table public.users(uid uuid primary key, role_id integer, dv_id bigint, allow_tools jsonb);
create table public.listings(id uuid primary key default gen_random_uuid(), property_id bigint, title text);
create table public.agents(id uuid primary key, name text, is_active boolean default true);
create table public.customers(id bigint primary key, dv_id bigint, first_name text, last_name text);
create collation public.dashboard_thai (provider = icu, locale = 'th');
create table public.bookings (
  id bigint generated by default as identity primary key,
  booking_code varchar(50) not null unique, listing_id uuid not null references public.listings(id),
  customer_id bigint, booking_type varchar(30) default 'booking', status varchar(50) default 'waiting',
  check_in date not null, check_out date not null,
  price_sell numeric(10,2) default 0, price_max numeric(10,2) default 0, deposit_amount numeric(10,2) default 0,
  extra_charge numeric(10,2) default 0, quantity integer default 1, details text, note text,
  created_by uuid, created_at timestamptz default now(), updated_at timestamptz default now(), houseid bigint,
  insurance numeric default 0, extra_person numeric default 0, checkin_time time, checkout_time time,
  agent_id uuid, payment_expires_at timestamptz,
  constraint no_overlapping_bookings exclude using gist
    (listing_id with =, daterange(check_in,check_out,'[)') with &&) where (status not in ('cancelled','rejected'))
);
insert into users values ('00000000-0000-4000-8000-000000000001',1,null,'{"allow_booking":true}');
insert into listings values ('00000000-0000-4000-8000-000000000010',100,'Synthetic house');
-- Synthetic audit adapter models actor attribution and no-op audit volume.
create table public.test_booking_audit(actor_id uuid, booking_id bigint, operation text);
create function public.test_audit_booking() returns trigger language plpgsql as $$
begin
  insert into public.test_booking_audit values(auth.uid(),coalesce(new.id,old.id),tg_op);
  return null;
end $$;
create trigger test_booking_audit after insert or update or delete on public.bookings
  for each row execute function public.test_audit_booking();
