import Link from "next/link";
import { dashboardShare } from "../../../lib/dashboard-calculations";
import { dashboardHref } from "../../../lib/dashboard-navigation";
import { type DashboardQuery, type DashboardReport } from "../../../lib/dashboard";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "../../ui/card";
import { DashboardAgencyRow, DashboardBookingRow, DashboardHouseRow } from "./dashboard-rows";
import { DashboardSummary } from "./dashboard-summary";

export function DashboardOverviewView({ report, query }: { report: DashboardReport; query: DashboardQuery }) {
  return <div className="space-y-5"><DashboardSummary report={report} query={query} />
    <details className="text-xs text-muted-foreground"><summary className="cursor-pointer py-3 focus-visible:outline-2">วิธีคำนวณยอดขาย</summary><p className="mt-2">ตามวันที่สร้างรายการ · สถานะปัจจุบัน · ยอดขายรวมเฉพาะรายการติดจอง</p></details>
    {report.sales.missingPrices > 0 && <p role="status" className="rounded-lg border p-3 text-sm">มีรายการติดจอง {report.sales.missingPrices} รายการที่ยังไม่ระบุยอด จึงนับจำนวนแต่ไม่นำยอดเงินมารวม</p>}
    {report.admin && <div className="grid items-start gap-5 lg:grid-cols-2"><Card><CardHeader><CardTitle className="flex items-center justify-between gap-3"><h2>ยอดขายเอเจนซี่</h2><Link href={dashboardHref(query, { view: "agencies", agenciesPage: 1 })} className="inline-flex min-h-11 shrink-0 items-center text-sm font-normal text-primary hover:underline focus-visible:outline-2">ดูทั้งหมด</Link></CardTitle><CardDescription>เฉพาะติดจอง · เรียงยอดขายสูงสุดก่อน</CardDescription></CardHeader><CardContent>{report.overview.topAgencies.length ? <div className="divide-y">{report.overview.topAgencies.map(agency => <DashboardAgencyRow key={agency.id ?? "unassigned"} agency={agency} sharePercent={dashboardShare(agency.amountCents, report.sales.amountCents)} href={dashboardHref(query, { view: "agency", from: "overview", agency: agency.id ?? "unassigned" })} />)}</div> : <p className="py-4 text-sm text-muted-foreground">ไม่มียอดขายติดจองในเดือนนี้</p>}{report.overview.agencyCount > 3 && <p className="pt-3 text-xs text-muted-foreground">อีก {report.overview.agencyCount - 3} เอเจนซี่</p>}</CardContent></Card>
      <Card><CardHeader><CardTitle className="flex items-center justify-between gap-3"><h2>บ้านที่เพิ่มใหม่</h2><Link href={dashboardHref(query, { view: "houses", housesPage: 1 })} className="inline-flex min-h-11 shrink-0 items-center text-sm font-normal text-primary hover:underline focus-visible:outline-2">ดูประวัติทั้งหมด</Link></CardTitle><CardDescription>{report.overview.newHouseCount.toLocaleString("th-TH")} หลังในเดือนที่เลือก</CardDescription></CardHeader><CardContent>{report.overview.recentHouses.length ? <div className="divide-y">{report.overview.recentHouses.map(house => <DashboardHouseRow key={house.id} house={house} href={dashboardHref(query, { view: "house", from: "overview", houseId: house.id })} />)}</div> : <p className="py-4 text-sm text-muted-foreground">ไม่มีบ้านเพิ่มใหม่ในเดือนนี้</p>}</CardContent></Card></div>}
    <Card><CardHeader><CardTitle className="flex items-center justify-between gap-3"><h2>การจองล่าสุด</h2><Link href={dashboardHref(query, { view: "bookings", page: 1 })} className="inline-flex min-h-11 shrink-0 items-center text-sm font-normal text-primary hover:underline focus-visible:outline-2">ดูรายการทั้งหมด</Link></CardTitle><CardDescription>สามรายการล่าสุดทุกสถานะ</CardDescription></CardHeader><CardContent>{report.overview.recentBookings.length ? <div className="divide-y">{report.overview.recentBookings.map(booking => <DashboardBookingRow key={booking.id} booking={booking} href={dashboardHref(query, { view: "booking", from: "overview", bookingId: booking.id })} />)}</div> : <p className="py-4 text-sm text-muted-foreground">ไม่มีการจองในเดือนนี้</p>}</CardContent></Card>
  </div>;
}
