CREATE EXTENSION IF NOT EXISTS "btree_gist" WITH SCHEMA "extensions";

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE SCHEMA IF NOT EXISTS "public";


ALTER SCHEMA "public" OWNER TO "pg_database_owner";


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE OR REPLACE FUNCTION "public"."handle_updated_at"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    AS $$
begin
  new.updated_at = now();
  return new;
end;
$$;


ALTER FUNCTION "public"."handle_updated_at"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."agent_accounts" (
    "id" "uuid" DEFAULT "extensions"."uuid_generate_v4"() NOT NULL,
    "agent_id" "uuid" NOT NULL,
    "bank_id" "uuid" NOT NULL,
    "account_number" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "agent_accounts_account_number_check" CHECK ((("char_length"("account_number") >= 1) AND ("char_length"("account_number") <= 30)))
);


ALTER TABLE "public"."agent_accounts" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."agents" (
    "id" "uuid" DEFAULT "extensions"."uuid_generate_v4"() NOT NULL,
    "name" "text" NOT NULL,
    "video_url" "text" NOT NULL,
    "is_active" boolean DEFAULT true NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "agents_name_check" CHECK ((("char_length"("name") >= 1) AND ("char_length"("name") <= 100))),
    CONSTRAINT "agents_video_url_check" CHECK (("video_url" ~ '^https://'::"text"))
);


ALTER TABLE "public"."agents" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."banks" (
    "id" "uuid" DEFAULT "extensions"."uuid_generate_v4"() NOT NULL,
    "name" "text" NOT NULL,
    "sort_order" integer DEFAULT 0 NOT NULL,
    CONSTRAINT "banks_name_check" CHECK ((("char_length"("name") >= 1) AND ("char_length"("name") <= 100))),
    CONSTRAINT "banks_sort_order_check" CHECK (("sort_order" >= 0))
);


ALTER TABLE "public"."banks" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."bedroom" (
    "id" bigint NOT NULL,
    "house_id" "uuid",
    "name" "jsonb",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone
);


ALTER TABLE "public"."bedroom" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."bedroom_facility" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone,
    "bedroom_id" bigint,
    "facility_id" bigint
);


ALTER TABLE "public"."bedroom_facility" OWNER TO "postgres";


ALTER TABLE "public"."bedroom_facility" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."bedroom_facility_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE "public"."bedroom" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."bedroom_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."bedroom_image" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone,
    "url" character varying DEFAULT 'NULL'::character varying,
    "description" "text" DEFAULT 'NULL'::"text",
    "bedroom_id" bigint,
    "facility_id" bigint
);


ALTER TABLE "public"."bedroom_image" OWNER TO "postgres";


ALTER TABLE "public"."bedroom_image" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."bedroom_image_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."booking_logs" (
    "id" bigint NOT NULL,
    "booking_id" "uuid" NOT NULL,
    "action" "text" NOT NULL,
    "old_status" "text",
    "new_status" "text",
    "changed_by" "uuid" NOT NULL,
    "notes" "text",
    "created_at" timestamp with time zone DEFAULT "now"(),
    "deville_id" bigint
);


ALTER TABLE "public"."booking_logs" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."booking_logs_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."booking_logs_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."booking_logs_id_seq" OWNED BY "public"."booking_logs"."id";



CREATE TABLE IF NOT EXISTS "public"."bookings" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "listings_id" "uuid",
    "guest_id" "uuid",
    "check_in" "date" NOT NULL,
    "check_out" "date" NOT NULL,
    "during" "daterange" GENERATED ALWAYS AS ("daterange"("check_in", "check_out", '[)'::"text")) STORED,
    "agent_id" bigint,
    "house_id" bigint,
    "details" "text",
    "codebooking" character varying
);


ALTER TABLE "public"."bookings" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."certificate_logs" (
    "id" "uuid" DEFAULT "extensions"."uuid_generate_v4"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "action" "text" NOT NULL,
    "target_type" "text" NOT NULL,
    "target_id" "uuid",
    "details" "jsonb" DEFAULT '{}'::"jsonb",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "certificate_logs_action_check" CHECK ((("char_length"("action") >= 1) AND ("char_length"("action") <= 50))),
    CONSTRAINT "certificate_logs_target_type_check" CHECK ((("char_length"("target_type") >= 1) AND ("char_length"("target_type") <= 30)))
);


ALTER TABLE "public"."certificate_logs" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."certificate_main_video" (
    "id" "uuid" DEFAULT "extensions"."uuid_generate_v4"() NOT NULL,
    "title" "text" NOT NULL,
    "description" "text" NOT NULL,
    "video_url" "text" NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "description_align" "text" DEFAULT 'center'::"text" NOT NULL,
    CONSTRAINT "certificate_main_video_description_align_check" CHECK (("description_align" = ANY (ARRAY['left'::"text", 'center'::"text", 'right'::"text"]))),
    CONSTRAINT "certificate_main_video_description_check" CHECK ((("char_length"("description") >= 1) AND ("char_length"("description") <= 2000))),
    CONSTRAINT "certificate_main_video_title_check" CHECK ((("char_length"("title") >= 1) AND ("char_length"("title") <= 200))),
    CONSTRAINT "certificate_main_video_video_url_check" CHECK (("video_url" ~ '^https://'::"text"))
);


ALTER TABLE "public"."certificate_main_video" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."facilities" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "name" character varying,
    "title" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone
);


ALTER TABLE "public"."facilities" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."house" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "h_id" bigint,
    "h_bedroom" integer,
    "h_toilet" integer,
    "h_extra" integer,
    "h_insurance" bigint,
    "h_location" "jsonb",
    "h_position" character varying DEFAULT 'NULL'::character varying,
    "h_zone" "jsonb",
    "h_village" "jsonb",
    "h_status" character varying DEFAULT 'offline'::character varying,
    "h_time_checkin" time with time zone,
    "h_time_checkout" time with time zone,
    "h_note" "text" DEFAULT 'NULL'::"text",
    "h_type" character varying DEFAULT 'NULL'::character varying,
    "h_owner" bigint,
    "line_group_id" "text" DEFAULT 'NULL'::"text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone,
    "h_name" character varying DEFAULT 'NULL'::character varying
);


ALTER TABLE "public"."house" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."images" (
    "id" bigint NOT NULL,
    "property_id" bigint NOT NULL,
    "cover_select" smallint DEFAULT 0,
    "image_name" character varying(255) NOT NULL,
    "image_url" character varying(255) NOT NULL,
    "caption" character varying(255) DEFAULT NULL::character varying,
    "create_by" bigint NOT NULL,
    "image_zone" character varying(30) NOT NULL,
    "image_move" bigint NOT NULL,
    "created_at" timestamp with time zone,
    "updated_at" timestamp with time zone,
    CONSTRAINT "images_create_by_check" CHECK (("create_by" > 0)),
    CONSTRAINT "images_id_check" CHECK (("id" > 0)),
    CONSTRAINT "images_image_move_check" CHECK (("image_move" > 0)),
    CONSTRAINT "images_image_zone_check" CHECK ((("image_zone")::"text" = ANY ((ARRAY['cover'::character varying, 'bedroom'::character varying, 'bathroom'::character varying, 'outside'::character varying, 'inside'::character varying, 'kitchen'::character varying, 'parking'::character varying, 'review'::character varying])::"text"[]))),
    CONSTRAINT "images_property_id_check" CHECK (("property_id" > 0))
);


ALTER TABLE "public"."images" OWNER TO "postgres";


ALTER TABLE "public"."images" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."images_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."line_notifications" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "property_id" bigint,
    "token_line" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."line_notifications" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."listing_facilities" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "listing_id" "uuid" DEFAULT "gen_random_uuid"(),
    "facility_id" "uuid" DEFAULT "gen_random_uuid"(),
    "message" "text",
    "value_boolean" boolean DEFAULT false,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone
);


ALTER TABLE "public"."listing_facilities" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."listing_prices" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "listing_id" "uuid" DEFAULT "gen_random_uuid"(),
    "day_of_week" smallint,
    "base_guests" integer,
    "deville_price" bigint,
    "agency_price" bigint,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone,
    "notes" "text"
);


ALTER TABLE "public"."listing_prices" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."listings" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "property_id" bigint,
    "title" character varying,
    "description" "text" DEFAULT 'NULL'::"text",
    "bedrooms" integer,
    "bathrooms" integer,
    "extra_beds" integer,
    "insurance_fee" bigint,
    "owner_id" bigint,
    "checkin_time" time without time zone,
    "checkout_time" time without time zone,
    "sort_order" integer,
    "notes" "text",
    "location_zone" character varying,
    "property_type" character varying,
    "rating" smallint,
    "max_guests" integer NOT NULL,
    "is_active" boolean,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone,
    "property_tags" "jsonb"
);


ALTER TABLE "public"."listings" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."profiles" (
    "id" bigint NOT NULL,
    "username" "text",
    "avatar_url" "text",
    "is_host" boolean DEFAULT false,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "uid" "uuid" DEFAULT "auth"."uid"()
);


ALTER TABLE "public"."profiles" OWNER TO "postgres";


ALTER TABLE "public"."profiles" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."profiles_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."roles" (
    "id" smallint NOT NULL,
    "name" json,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."roles" OWNER TO "postgres";


ALTER TABLE "public"."roles" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."roles_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."users" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "username" character varying DEFAULT 'NULL'::character varying,
    "password" "text" DEFAULT ''::"text",
    "name" character varying,
    "tel" character varying,
    "email" character varying,
    "role_id" smallint DEFAULT '3'::smallint,
    "team_id" smallint,
    "allow_tools" "jsonb",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "dv_id" bigint,
    "uid" "uuid" DEFAULT "auth"."uid"(),
    "mid" bigint
);


ALTER TABLE "public"."users" OWNER TO "postgres";


ALTER TABLE ONLY "public"."booking_logs" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."booking_logs_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."agent_accounts"
    ADD CONSTRAINT "agent_accounts_agent_id_bank_id_account_number_key" UNIQUE ("agent_id", "bank_id", "account_number");



ALTER TABLE ONLY "public"."agent_accounts"
    ADD CONSTRAINT "agent_accounts_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."agents"
    ADD CONSTRAINT "agents_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."banks"
    ADD CONSTRAINT "banks_name_key" UNIQUE ("name");



ALTER TABLE ONLY "public"."banks"
    ADD CONSTRAINT "banks_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."bedroom_facility"
    ADD CONSTRAINT "bedroom_facility_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."bedroom_image"
    ADD CONSTRAINT "bedroom_image_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."bedroom"
    ADD CONSTRAINT "bedroom_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."booking_logs"
    ADD CONSTRAINT "booking_logs_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."bookings"
    ADD CONSTRAINT "bookings_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."certificate_logs"
    ADD CONSTRAINT "certificate_logs_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."certificate_main_video"
    ADD CONSTRAINT "certificate_main_video_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."facilities"
    ADD CONSTRAINT "facilities_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."house"
    ADD CONSTRAINT "house_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."images"
    ADD CONSTRAINT "images_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."line_notifications"
    ADD CONSTRAINT "line_notifications_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."listing_facilities"
    ADD CONSTRAINT "listing_facilities_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."listing_prices"
    ADD CONSTRAINT "listing_prices_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."listings"
    ADD CONSTRAINT "listings_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."bookings"
    ADD CONSTRAINT "no_overlapping_bookings" EXCLUDE USING "gist" ("listings_id" WITH =, "during" WITH &&);



ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_uid_unique" UNIQUE ("uid");



ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_username_key" UNIQUE ("username");



ALTER TABLE ONLY "public"."roles"
    ADD CONSTRAINT "roles_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "users_dv_id_unique" UNIQUE ("dv_id");



ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "users_pkey" PRIMARY KEY ("id");



CREATE UNIQUE INDEX "certificate_main_video_singleton" ON "public"."certificate_main_video" USING "btree" ((true));



CREATE INDEX "idx_agent_accounts_agent_id" ON "public"."agent_accounts" USING "btree" ("agent_id");



CREATE INDEX "idx_agent_accounts_bank_id" ON "public"."agent_accounts" USING "btree" ("bank_id");



CREATE INDEX "idx_agents_created_at" ON "public"."agents" USING "btree" ("created_at");



CREATE INDEX "idx_agents_is_active" ON "public"."agents" USING "btree" ("is_active") WHERE ("is_active" = true);



CREATE INDEX "idx_banks_sort_order" ON "public"."banks" USING "btree" ("sort_order");



CREATE INDEX "idx_certificate_logs_action" ON "public"."certificate_logs" USING "btree" ("action");



CREATE INDEX "idx_certificate_logs_created_at" ON "public"."certificate_logs" USING "btree" ("created_at" DESC);



CREATE OR REPLACE TRIGGER "on_agents_updated" BEFORE UPDATE ON "public"."agents" FOR EACH ROW EXECUTE FUNCTION "public"."handle_updated_at"();



CREATE OR REPLACE TRIGGER "on_certificate_main_video_updated" BEFORE UPDATE ON "public"."certificate_main_video" FOR EACH ROW EXECUTE FUNCTION "public"."handle_updated_at"();



ALTER TABLE ONLY "public"."agent_accounts"
    ADD CONSTRAINT "agent_accounts_agent_id_fkey" FOREIGN KEY ("agent_id") REFERENCES "public"."agents"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."agent_accounts"
    ADD CONSTRAINT "agent_accounts_bank_id_fkey" FOREIGN KEY ("bank_id") REFERENCES "public"."banks"("id") ON DELETE RESTRICT;



ALTER TABLE ONLY "public"."bedroom_facility"
    ADD CONSTRAINT "bedroom_facility_bedroom_id_fkey" FOREIGN KEY ("bedroom_id") REFERENCES "public"."bedroom"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."bedroom"
    ADD CONSTRAINT "bedroom_house_id_fkey" FOREIGN KEY ("house_id") REFERENCES "public"."house"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."bedroom_image"
    ADD CONSTRAINT "bedroom_image_bedroom_id_fkey" FOREIGN KEY ("bedroom_id") REFERENCES "public"."bedroom"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."house"
    ADD CONSTRAINT "house_h_owner_fkey" FOREIGN KEY ("h_owner") REFERENCES "public"."users"("dv_id");



ALTER TABLE ONLY "public"."listing_facilities"
    ADD CONSTRAINT "listing_facilities_facility_id_fkey" FOREIGN KEY ("facility_id") REFERENCES "public"."facilities"("id") ON UPDATE CASCADE ON DELETE SET NULL;



ALTER TABLE ONLY "public"."listing_facilities"
    ADD CONSTRAINT "listing_facilities_listing_id_fkey" FOREIGN KEY ("listing_id") REFERENCES "public"."listings"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."listing_prices"
    ADD CONSTRAINT "listing_prices_listing_id_fkey" FOREIGN KEY ("listing_id") REFERENCES "public"."listings"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_uid_fkey" FOREIGN KEY ("uid") REFERENCES "auth"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "users_role_id_fkey" FOREIGN KEY ("role_id") REFERENCES "public"."roles"("id");



ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "users_uid_fkey" FOREIGN KEY ("uid") REFERENCES "auth"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;



CREATE POLICY "Enable read access for all users" ON "public"."listings" FOR SELECT TO "authenticated", "anon" USING (true);



CREATE POLICY "Users can insert own profile" ON "public"."profiles" FOR INSERT WITH CHECK (("auth"."uid"() = "uid"));



CREATE POLICY "Users can read own row" ON "public"."users" FOR SELECT TO "authenticated" USING (("uid" = "auth"."uid"()));



CREATE POLICY "Users can update own profile" ON "public"."profiles" FOR UPDATE USING (("auth"."uid"() = "uid")) WITH CHECK (("auth"."uid"() = "uid"));



CREATE POLICY "Users can view own profile" ON "public"."profiles" FOR SELECT USING (("auth"."uid"() = "uid"));



ALTER TABLE "public"."agent_accounts" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."agents" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "allow delete" ON "public"."facilities" FOR DELETE TO "authenticated" USING (true);



CREATE POLICY "allow delete" ON "public"."listing_prices" FOR DELETE USING (true);



CREATE POLICY "allow images" ON "public"."images" TO "anon" USING (true) WITH CHECK (true);



CREATE POLICY "allow insert" ON "public"."facilities" FOR INSERT TO "authenticated" WITH CHECK (true);



CREATE POLICY "allow insert" ON "public"."listing_facilities" FOR INSERT TO "authenticated" WITH CHECK (true);



CREATE POLICY "allow insert" ON "public"."listing_prices" FOR INSERT TO "authenticated" WITH CHECK (true);



CREATE POLICY "allow select" ON "public"."facilities" FOR SELECT TO "authenticated", "anon" USING (true);



CREATE POLICY "allow selected" ON "public"."listing_facilities" FOR SELECT TO "authenticated", "anon" USING (true);



CREATE POLICY "allow selected" ON "public"."listing_prices" FOR SELECT TO "authenticated", "anon" USING (true);



CREATE POLICY "allow updated" ON "public"."facilities" FOR UPDATE TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "allow updated" ON "public"."listing_facilities" FOR UPDATE TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "allow updated" ON "public"."listing_prices" FOR UPDATE TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "anon: read active agents" ON "public"."agents" FOR SELECT TO "anon" USING (("is_active" = true));



CREATE POLICY "anon: read agent_accounts of active agents" ON "public"."agent_accounts" FOR SELECT TO "anon" USING ((EXISTS ( SELECT 1
   FROM "public"."agents"
  WHERE (("agents"."id" = "agent_accounts"."agent_id") AND ("agents"."is_active" = true)))));



CREATE POLICY "anon: read banks" ON "public"."banks" FOR SELECT TO "anon" USING (true);



CREATE POLICY "anon: read certificate_main_video" ON "public"."certificate_main_video" FOR SELECT TO "anon" USING (true);



CREATE POLICY "auth: delete agent_accounts" ON "public"."agent_accounts" FOR DELETE TO "authenticated" USING (true);



CREATE POLICY "auth: delete agents" ON "public"."agents" FOR DELETE TO "authenticated" USING (true);



CREATE POLICY "auth: delete banks" ON "public"."banks" FOR DELETE TO "authenticated" USING (true);



CREATE POLICY "auth: insert agent_accounts" ON "public"."agent_accounts" FOR INSERT TO "authenticated" WITH CHECK (true);



CREATE POLICY "auth: insert agents" ON "public"."agents" FOR INSERT TO "authenticated" WITH CHECK (true);



CREATE POLICY "auth: insert banks" ON "public"."banks" FOR INSERT TO "authenticated" WITH CHECK (true);



CREATE POLICY "auth: insert certificate_logs" ON "public"."certificate_logs" FOR INSERT TO "authenticated" WITH CHECK (true);



CREATE POLICY "auth: insert certificate_main_video" ON "public"."certificate_main_video" FOR INSERT TO "authenticated" WITH CHECK (true);



CREATE POLICY "auth: read all agent_accounts" ON "public"."agent_accounts" FOR SELECT TO "authenticated" USING (true);



CREATE POLICY "auth: read all agents" ON "public"."agents" FOR SELECT TO "authenticated" USING (true);



CREATE POLICY "auth: read banks" ON "public"."banks" FOR SELECT TO "authenticated" USING (true);



CREATE POLICY "auth: read certificate_logs" ON "public"."certificate_logs" FOR SELECT TO "authenticated" USING (true);



CREATE POLICY "auth: read certificate_main_video" ON "public"."certificate_main_video" FOR SELECT TO "authenticated" USING (true);



CREATE POLICY "auth: update agent_accounts" ON "public"."agent_accounts" FOR UPDATE TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "auth: update agents" ON "public"."agents" FOR UPDATE TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "auth: update banks" ON "public"."banks" FOR UPDATE TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "auth: update certificate_main_video" ON "public"."certificate_main_video" FOR UPDATE TO "authenticated" USING (true) WITH CHECK (true);



ALTER TABLE "public"."banks" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."bedroom" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."bedroom_facility" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."bedroom_image" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."booking_logs" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."bookings" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."certificate_logs" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."certificate_main_video" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."facilities" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."house" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."images" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."line_notifications" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."listing_facilities" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."listing_prices" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."listings" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."profiles" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."roles" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "select_public" ON "public"."images" FOR SELECT TO "anon" USING (true);



CREATE POLICY "selected" ON "public"."users" FOR SELECT TO "anon" USING (true);



CREATE POLICY "update policies allow" ON "public"."listings" FOR UPDATE TO "authenticated" USING (true) WITH CHECK (true);



ALTER TABLE "public"."users" ENABLE ROW LEVEL SECURITY;


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";



GRANT ALL ON FUNCTION "public"."handle_updated_at"() TO "anon";
GRANT ALL ON FUNCTION "public"."handle_updated_at"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."handle_updated_at"() TO "service_role";



GRANT ALL ON TABLE "public"."agent_accounts" TO "anon";
GRANT ALL ON TABLE "public"."agent_accounts" TO "authenticated";
GRANT ALL ON TABLE "public"."agent_accounts" TO "service_role";



GRANT ALL ON TABLE "public"."agents" TO "anon";
GRANT ALL ON TABLE "public"."agents" TO "authenticated";
GRANT ALL ON TABLE "public"."agents" TO "service_role";



GRANT ALL ON TABLE "public"."banks" TO "anon";
GRANT ALL ON TABLE "public"."banks" TO "authenticated";
GRANT ALL ON TABLE "public"."banks" TO "service_role";



GRANT ALL ON TABLE "public"."bedroom" TO "anon";
GRANT ALL ON TABLE "public"."bedroom" TO "authenticated";
GRANT ALL ON TABLE "public"."bedroom" TO "service_role";



GRANT ALL ON TABLE "public"."bedroom_facility" TO "anon";
GRANT ALL ON TABLE "public"."bedroom_facility" TO "authenticated";
GRANT ALL ON TABLE "public"."bedroom_facility" TO "service_role";



GRANT ALL ON SEQUENCE "public"."bedroom_facility_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."bedroom_facility_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."bedroom_facility_id_seq" TO "service_role";



GRANT ALL ON SEQUENCE "public"."bedroom_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."bedroom_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."bedroom_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."bedroom_image" TO "anon";
GRANT ALL ON TABLE "public"."bedroom_image" TO "authenticated";
GRANT ALL ON TABLE "public"."bedroom_image" TO "service_role";



GRANT ALL ON SEQUENCE "public"."bedroom_image_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."bedroom_image_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."bedroom_image_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."booking_logs" TO "anon";
GRANT ALL ON TABLE "public"."booking_logs" TO "authenticated";
GRANT ALL ON TABLE "public"."booking_logs" TO "service_role";



GRANT ALL ON SEQUENCE "public"."booking_logs_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."booking_logs_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."booking_logs_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."bookings" TO "anon";
GRANT ALL ON TABLE "public"."bookings" TO "authenticated";
GRANT ALL ON TABLE "public"."bookings" TO "service_role";



GRANT ALL ON TABLE "public"."certificate_logs" TO "anon";
GRANT ALL ON TABLE "public"."certificate_logs" TO "authenticated";
GRANT ALL ON TABLE "public"."certificate_logs" TO "service_role";



GRANT ALL ON TABLE "public"."certificate_main_video" TO "anon";
GRANT ALL ON TABLE "public"."certificate_main_video" TO "authenticated";
GRANT ALL ON TABLE "public"."certificate_main_video" TO "service_role";



GRANT ALL ON TABLE "public"."facilities" TO "anon";
GRANT ALL ON TABLE "public"."facilities" TO "authenticated";
GRANT ALL ON TABLE "public"."facilities" TO "service_role";



GRANT ALL ON TABLE "public"."house" TO "anon";
GRANT ALL ON TABLE "public"."house" TO "authenticated";
GRANT ALL ON TABLE "public"."house" TO "service_role";



GRANT ALL ON TABLE "public"."images" TO "anon";
GRANT ALL ON TABLE "public"."images" TO "authenticated";
GRANT ALL ON TABLE "public"."images" TO "service_role";



GRANT ALL ON SEQUENCE "public"."images_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."images_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."images_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."line_notifications" TO "anon";
GRANT ALL ON TABLE "public"."line_notifications" TO "authenticated";
GRANT ALL ON TABLE "public"."line_notifications" TO "service_role";



GRANT ALL ON TABLE "public"."listing_facilities" TO "anon";
GRANT ALL ON TABLE "public"."listing_facilities" TO "authenticated";
GRANT ALL ON TABLE "public"."listing_facilities" TO "service_role";



GRANT ALL ON TABLE "public"."listing_prices" TO "anon";
GRANT ALL ON TABLE "public"."listing_prices" TO "authenticated";
GRANT ALL ON TABLE "public"."listing_prices" TO "service_role";



GRANT ALL ON TABLE "public"."listings" TO "anon";
GRANT ALL ON TABLE "public"."listings" TO "authenticated";
GRANT ALL ON TABLE "public"."listings" TO "service_role";



GRANT ALL ON TABLE "public"."profiles" TO "anon";
GRANT ALL ON TABLE "public"."profiles" TO "authenticated";
GRANT ALL ON TABLE "public"."profiles" TO "service_role";



GRANT ALL ON SEQUENCE "public"."profiles_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."profiles_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."profiles_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."roles" TO "anon";
GRANT ALL ON TABLE "public"."roles" TO "authenticated";
GRANT ALL ON TABLE "public"."roles" TO "service_role";



GRANT ALL ON SEQUENCE "public"."roles_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."roles_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."roles_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."users" TO "anon";
GRANT ALL ON TABLE "public"."users" TO "authenticated";
GRANT ALL ON TABLE "public"."users" TO "service_role";



ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";






