-- Upgrade only an EMPTY legacy booking schema. Preserve table identities and RLS.
do $$
begin
  if exists(select 1 from information_schema.columns where table_schema='public'
    and table_name='bookings' and column_name='id' and data_type='uuid') then
    lock table public.bookings, public.booking_logs in access exclusive mode;
    if exists(select 1 from public.bookings) or exists(select 1 from public.booking_logs) then
      raise exception 'Legacy bookings must be empty; populated databases require an explicit ID mapping';
    end if;
    alter table public.bookings alter column id drop default;
    alter table public.bookings alter column id type bigint using null::bigint;
    alter table public.bookings alter column id add generated by default as identity;
    alter table public.bookings rename column listings_id to listing_id;
    alter table public.bookings rename column house_id to houseid;
    alter table public.bookings rename column codebooking to booking_code;
    alter table public.bookings alter column booking_code type varchar(50);
    alter table public.bookings alter column booking_code set not null;
    alter table public.bookings alter column listing_id set not null;
    alter table public.bookings add column customer_id bigint,
      add column booking_type varchar(30) default 'booking',
      add column status varchar(50) default 'waiting',
      add column price_sell numeric default 0, add column price_max numeric default 0,
      add column deposit_amount numeric default 0, add column extra_charge numeric default 0,
      add column quantity integer default 1, add column note text,
      add column created_by uuid references auth.users(id),
      add column created_at timestamptz default now(), add column updated_at timestamptz default now();
    alter table public.bookings add constraint bookings_booking_code_key unique(booking_code);
    alter table public.bookings add constraint bookings_listing_id_fkey foreign key(listing_id) references public.listings(id) on delete cascade;
    alter table public.bookings drop constraint no_overlapping_bookings;
    alter table public.bookings add constraint no_overlapping_bookings exclude using gist
      (listing_id with =, daterange(check_in,check_out,'[)') with &&)
      where (status not in ('cancelled','rejected'));
    alter table public.booking_logs alter column booking_id type bigint using null::bigint;
    alter table public.booking_logs alter column changed_by drop not null;
    alter table public.booking_logs add column old_data jsonb, add column new_data jsonb,
      add column changed_fields jsonb, add column performed_by uuid references auth.users(id);
    alter table public.booking_logs add constraint booking_logs_booking_id_fkey
      foreign key(booking_id) references public.bookings(id) on delete cascade;
  end if;
end;
$$;

-- Existing modern customer tables are left untouched.
do $$
begin
if to_regclass('public.customers') is null then
create table public.customers (
  id bigint generated by default as identity primary key,
  customer_type varchar(20) default 'individual', title varchar(20),
  first_name varchar(100) not null, last_name varchar(100), email varchar(150),
  phone varchar(20) not null, secondary_phone varchar(20), line_id varchar(50),
  id_card_no varchar(20), passport_no varchar(50), nationality varchar(50) default 'Thai',
  date_of_birth date, tax_id varchar(20), tax_company_name varchar(255),
  tax_head_office boolean default true, tax_branch_code varchar(10) default '00000',
  tax_address text, address text, sub_district varchar(100), district varchar(100),
  province varchar(100), postal_code varchar(10), country varchar(100) default 'Thailand',
  preferred_language varchar(10) default 'th', special_requests text,
  vip_status boolean default false, notes text, created_at timestamptz default now(),
  updated_at timestamptz default now(), dv_id bigint
);
revoke all on public.customers from anon, authenticated;
revoke all on sequence public.customers_id_seq from anon, authenticated;
grant select,insert,update,delete on public.customers to service_role;
grant usage,select on sequence public.customers_id_seq to service_role;
end if;
end;
$$;

do $$
begin
  if not exists(select 1 from pg_constraint where conrelid='public.bookings'::regclass
    and contype='f' and confrelid='public.customers'::regclass) then
    alter table public.bookings add constraint bookings_customer_id_fkey foreign key(customer_id)
      references public.customers(id) on delete set null;
  end if;
end;
$$;

-- No policy or RLS changes. New customer grants above are server-only.

-- Existing modern audit triggers are retained. Install a trigger only when absent.
do $$
begin
  if not exists(select 1 from pg_trigger where tgrelid='public.bookings'::regclass
    and not tgisinternal and tgname='trigger_booking_audit_log') then
    execute $ddl$
      create function public.log_calendar_booking_changes() returns trigger
      language plpgsql security definer set search_path=pg_catalog,public as $body$
      declare changes jsonb := '{}'::jsonb; key text;
      begin
        if tg_op='UPDATE' then
          for key in select jsonb_object_keys(to_jsonb(new)) loop
            if (to_jsonb(old)->key) is distinct from (to_jsonb(new)->key) then
              changes := jsonb_set(changes,array[key],jsonb_build_object('old',to_jsonb(old)->key,'new',to_jsonb(new)->key));
            end if;
          end loop;
          insert into public.booking_logs(booking_id,action,old_data,new_data,changed_fields,performed_by)
          values(new.id,'UPDATE',to_jsonb(old),to_jsonb(new),changes,auth.uid());
        elsif tg_op='INSERT' then
          insert into public.booking_logs(booking_id,action,new_data,performed_by)
          values(new.id,'INSERT',to_jsonb(new),auth.uid());
        end if;
        return new;
      end;
      $body$;
    $ddl$;
    create trigger trigger_booking_audit_log after insert or update on public.bookings
      for each row execute function public.log_calendar_booking_changes();
  end if;
end;
$$;
notify pgrst, 'reload schema';
